#
# This file contains configuration flags to customize your site
#

theme: minima

# Name of your site (displayed in the header)
name: Techmew

# Short bio or description (displayed in the header)
description: AI & Web3 Game Auto Blog

# URL of your avatar or profile pic
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Footer social links
footer-links:
  github: techmew/techmew.github.io
  twitter: techmew

# URL of your site (optional but recommended for sitemap and feeds)
url: "https://techmew.github.io"

# If hosted at a project repo like https://techmew.github.io/jekyll-now
baseurl: "/jekyll-now"

# Permalink style (URL pattern for posts)
permalink: /:title/

# Disqus shortname (if you use Disqus comments)
disqus:

# Google Analytics tracking code (if you use GA)
google_analytics:

# Markdown processor settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass settings
sass:
  style: :expanded

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
