name: Blog Update

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: Run blog generation script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          HORDE_API_KEY: ${{ secrets.HORDE_API_KEY }}
        run: python generate_blog.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add _posts/*.md assets/images/*.png
          git commit -m "Add new blog posts" || echo "No changes to commit"
          git push
